### ISSUE TITLE
overwrite malloc/free with dlopen-ed library is not working

### ISSUE THREAD

**Issue by Rishi513719** [WuBingzheng/libleak#10]
Hi,
We are using dlopen and dlsym calls to overwrite malloc function.
By doing this we end up with application crash due to recursive call of malloc function call.
We have attached the application code as well as modified libleak.c.

Please can you help us to understand what's going wrong.

[common_include.txt](https://github.com/WuBingzheng/libleak/files/3916396/common_include.txt)
[libleak.txt](https://github.com/WuBingzheng/libleak/files/3916397/libleak.txt)
[app.txt](https://github.com/WuBingzheng/libleak/files/3916406/app.txt)

Thanks,
Raghu

**Comment by WuBingzheng** [comment]
I guess the difference is that:

in libleak:

    APP -> malloc(=libleak:malloc) -> leak_real_malloc(=libc:malloc)

while in your program:

    APP -> malloc(=stub_malloc) -> leak_real_malloc(=stub_malloc)

where `->` means "function call", and `=` means "which is".

So, in libleak, there are 2 "malloc" functions: `libleak:malloc` and `libc:malloc`.
while in your program there is only 1, then `stub_malloc` calls `stub_malloc` recursively.

**Comment by Rishi513719** [comment]
Hi WuBingzheng,

Thanks a lot for your valuable and quick reply.
As suggested by you, we have modified the source code and application and now application is not crashed. 

Thanks a lot.
