### ISSUE TITLE
can't head file such as "wuy_dict.h"

### ISSUE THREAD

**Issue by zhaohongjian520** [WuBingzheng/libleak#11]
There are no head file include wuy_dict.h wuy_list.h and wuy_pool.h, can you add it?

**Comment by WuBingzheng** [comment]
They are in another project as a submodule of libleak.

You should clone the code as:

    $ git clone --recursive https://github.com/WuBingzheng/libleak.git

Or download the libwuya from http://github.com/wubingzheng/libwuya
