### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by M-Reimer** [WuBingzheng/libleak#13]
I want to find a memory leak in a bigger program: http://tvdr.de/

But all that libleak produces is a over 100MB log with cryptic information. How should I find the relevant parts in 1991508 lines of log?

What this (probably very useful) tool really needs is some kind of tutorial on how to use it!

**Comment by WuBingzheng** [comment]
I add "READ LOG" section in README. Please check it out.

Maybe you could stop the output more early to avoid too big log.

**Comment by WuBingzheng** [comment]
I add 2 features which both can reduce log size:
1.  LEAK_AFTER, skip initial phase to avoid many logs;
2. LEAK_LIB_BLACKLIST, to disable some shared libraries.
