### ISSUE TITLE
Core dumped on Jetson NANO

### ISSUE THREAD

**Issue by stiv-yakovenko** [WuBingzheng/libleak#16]
I'm trying to use libleak on jetson nano, but i get this error:

```
izuser@nano:~/jsoft-1.0/dgpu_core$ LD_PRELOAD=/home/izuser/libleak/libleak.so ./build/dgpu_core
Aborted (core dumped)
```

without LD_PRELOAD it works correctly. How can I fix/diagnose this problem?

**Comment by WuBingzheng** [comment]
Please paste the coredump's call-stack here.

    $ gdb ./build/dgpu_core core
    (gdb) bt
