### ISSUE TITLE
Output has no backtrace 

### ISSUE THREAD

**Issue by jampalanca** [WuBingzheng/libleak#21]
Hello and thank you for this tool. 
I tried using this tool in ARM to check a possible memory leak in our system but when I check the output the backtrace is not shown. 

# start detect. expire=300s
callstack[1] expires. count=1 size=216/216 alloc=211774 free=211482
callstack[1] expires. count=2 size=16/232 alloc=211774 free=211482
callstack[1] expires. count=3 size=216/448 alloc=211774 free=211482
callstack[1] expires. count=4 size=16/464 alloc=211774 free=211482
callstack[1] expires. count=5 size=2040/2504 alloc=211898 free=211606
callstack[1] expires. count=6 size=216/2720 alloc=214351 free=214055
callstack[1] expires. count=7 size=16/2736 alloc=214351 free=214055
callstack[1] expires. count=8 size=216/2952 alloc=214351 free=214055
callstack[1] expires. count=9 size=16/2968 alloc=214351 free=214055
callstack[1] expires. count=10 size=216/3184 alloc=218767 free=218467
callstack[1] expires. count=11 size=16/3200 alloc=218767 free=218467
callstack[1] expires. count=12 size=216/3416 alloc=218827 free=218527
callstack[1] expires. count=13 size=16/3432 alloc=218827 free=218527

Any advice on what could cause this?

**Comment by WuBingzheng** [comment]
`libleak` print backtrace by calling `libbacktract`, and I do not know much about `libbacktrace` internal.

Maybe you can add some debug log [here](https://github.com/WuBingzheng/libleak/blob/master/libleak.c#L414) to see what happened.

**Comment by jampalanca** [comment]
I tried putting a debug message to check the "cs->ip_num" it always return zero. I think I'm not getting any backtrace. 
I believe this is not a libleak issue.
Will close this issue now.
Thanks for the support!

**Comment by ierturk** [comment]
Hi @jampalanca,

It may be too late but, I experienced the same problem and resolve it as follow. It si regarding the `CFLAGS` for building `Libleak`.

```
# For ARM Embedded, to work printing backtrace properly it should be added the following flags into CFLAGS
# -funwind-tables -mapcs-frame -rdynamic
# reference https://stackoverflow.com/questions/38565589/gcc-arm-printing-back-trace-when-exception-occurred
# Add your cross compiler bin dir that contains gcc executable as armv7l-XXXX-linux-gnueabi-gcc into your PATH environment variable

$ mkdir memory_leak && cd memory_leak

# buid Libbacktrace
$ git clone https://github.com/ianlancetaylor/libbacktrace.git
$ cd libbacktrace
$ ./configure --build=x86_64-linux-gnu --host=armv7l-XXXX-linux-gnueabi --target=armv7l-XXXX-linux-gnueabi --prefix=/mnt/Work/memory_leak/libs_armv7l/libbacktrace --enable-static
$ make
$ make install

# Build Libleak
$ cd ..
$ git clone --recursive https://github.com/WuBingzheng/libleak.git
$ cd libleak

# Modify Libleak Makefile
CROSS_COMPILE = armv7l-XXXX-linux-gnueabi-
CC = $(CROSS_COMPILE)gcc

INC_DIR += ../libs_armv7l/libbacktrace/include

CFLAGS = -std=c99 -g -O2 -Wall -fPIC -funwind-tables -mapcs-frame -rdynamic -Ilibwuya -I$(INC_DIR) -rdynamic
LDFLAGS = -Llibwuya -L../libs_armv7l/libbacktrace/lib

libleak.so: libleak.o
	CFLAGS='-std=c99 -g -O2 -Wall -fPIC -funwind-tables -mapcs-frame -rdynamic' make -C libwuya
	$(CC) -shared -o $@ $^ $(LDFLAGS) -lwuya -lpthread -ldl -lbacktrace

clean:
	rm -f libleak.so *.o


# Modify Libwuya Makefile
CROSS_COMPILE = armv7l-XXXX-linux-gnueabi-
CC = $(CROSS_COMPILE)gcc

CFLAGS += -g -Wall -O2

all: libwuya.a

libwuya.a: wuy_dict.o wuy_pool.o wuy_heap.o wuy_event.o wuy_sockaddr.o wuy_skiplist.o
	ar rcs $@ $^

clean:
	rm -f *.o libwuya.a

# run make in libleak directory
make

```
Hope this works for you as well.

ierturk
