### ISSUE TITLE
Not sure whether it is an issue or not.

### ISSUE THREAD

**Issue by Gongnai** [WuBingzheng/libleak#6]
Have downloaded source code :
-rw-rw-r--    1 zhaog    man          3.2K Jun  9 23:37 README.md
-rw-rw-r--    1 zhaog    man           198 Jun  9 23:37 Makefile
-rw-rw-r--    1 zhaog    man           15K Jun  9 23:37 libleak.c
drwxrwxr-x    2 zhaog    man           152 Jun 12 10:51 libwuya/

Tried to build it up by kicking off command make in below old linux box
Linux ceres 2.4.21-32.ELsmp #1 SMP Fri Apr 15 21:17:59 EDT 2005 i686 i686 i386 GNU/Linux

But looks like it was failed with bunch of errors.
Build log was attached. Could you please take a look?
Thanks
[build.log](https://github.com/WuBingzheng/libleak/files/3282004/build.log)

**Comment by WuBingzheng** [comment]
Is the `libwuya` empty?

`libwuya` is another project and used as git-submodule here.
So you can get it by `git clone` with `--recursive`:

    $ git clone --recursive https://github.com/WuBingzheng/libleak.git

or you can download its source from [here](https://github.com/WuBingzheng/libwuya) to `libwuya/` directory.

**Comment by Gongnai** [comment]
Yes, libwuya is empty.
will give it a shot after downloading it.

Thanks for your quick reply.

On Jun. 13, 2019 at 3:32 a.m., <WuBingzheng <notifications@github.com>>
wrote:

Is the libwuya empty?

libwuya is another project and used as git-submodule here.
So you can get it by git clone with --recursive:

$ git clone --recursive https://github.com/WuBingzheng/libleak.git

or you can download its source from here
<https://github.com/WuBingzheng/libwuya> to libwuya/ directory.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/WuBingzheng/libleak/issues/6?email_source=notifications&email_token=AMANXRLLJPEZ65EZ3MCDFVDP2HZYDA5CNFSM4HXKDAKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXSZOLI#issuecomment-501585709>,
or mute the thread

**Comment by Gongnai** [comment]
Hi Wubing,
Thanks for your quick reply. libwuya was built successfully with a minor defect that I have fixed on my side.
Compiler of my linux box is really old by using C99 mode. And it can *not* declare a variable and initialize it in one shot. Have to split it into 2 lines like below:

For example:
File wuy_skiplist.c

Before:
for ( int i = level - 1; i > 0; i--) {
  ..
}

After:
int i;
for (i = level - 1; i > 0; i--) {
  ..
}

File: wuy_heap.c
Before:
for ( size_t i = 0; i < heap->count; i++) {
  ...
}

After:
 size_t i;
for ( size_t i = 0; i < heap->count; i++) {
  ...
}

Other than that, it is pretty good.
Thanks

**Comment by Gongnai** [comment]
And also a question for you is:
File wuy_dict.h
Can't find where _ibck_end was declared :(
...
 162 /**
    163  * @brief Iterate over a dict.
    164  */
    165
    166 wuy_hlist_head_t *_ibck_start;
    167 wuy_hlist_head_t *_ib;
    168
    169 #define wuy_dict_iter(dict, p) \
    170   for (_ibck_start = NULL, *_ibck_end = NULL; \
    171     _wuy_dict_iter_buckets(dict, &_ibck_start, &_ibck_end); ) \
    172     for (_ib = _ibck_start; _ib < _ibck_end; _ib++) \
    173       wuy_hlist_iter(_ib, p)
...

**Comment by Gongnai** [comment]
Wubing, 

A question for you. 
If an application has a kind of cache memory , that means some memory will stay for ever except application exits. 

What kind of expire threshold will be set under this case? Maybe around 5mins?
And some memory was really leaking like memory will be increasing every 20 secs.
Any ideas or suggestions on this scenario? 

Thanks in advance.
Gongnai

**Comment by WuBingzheng** [comment]
If the leak happens at cache memory, which means some place allocates memory from the cache but does not put back to the cache forever, it's hard to find the leak by `libleak`. However if most of the cache memory is allocated by the leak-place, which is very possible, the leak-place will be shown many times in `libleak` output and you can guess it.

If the leak happens not at cache memory, you can focus on non-cache-memory in `libleak` output and should find the leak-place easily.

In both case, 20secs or 1min should be OK.

**Comment by Gongnai** [comment]
Thanks for your reply. However there was a core dump when have tried to kick off leaklib, looks like 32bits linux box doesn't like leaklib. I can't spend extra time on digging into this core file. 
Will use Valgrind then. Anyways thanks for your time.

**Comment by WuBingzheng** [comment]
I did not test on 32bit linux.
I will test it later at free time.
