### ISSUE TITLE
Unable to get the stack

### ISSUE THREAD

**Issue by Rishi513719** [WuBingzheng/libleak#9]
Below is the sample code with which I want to try this shared library usage.
File: example.c

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
int main()
{
    int i;
    int *ptr = NULL;
    ptr = malloc(sizeof(int) * 1000);
    for(i=0; i<10;i++)
    {
        printf("*********\n");
        sleep(1);
    }
    return 0;
}

Compiled as below:
gcc -c -g -Wall -o example.o example.c
gcc -export-dynamic -o prog example.o

Below is the execution:
LD_PRELOAD=./libleak.so LEAK_PID_CHECK=10 ./prog

To see the call stack, there is a file created with PID as: /tmp/libleak.$(PID)

But the content in the file is shown as below.
# start detect. expire=1000s

# callstack statistics: (in ascending order)

 Callstack is empty. Kindly let me know what mistake I have done in this? Please bear with me as I am not completely aware of the concepts.

Regards,
Raghu

**Comment by WuBingzheng** [comment]
1. You should set expire time less than 10s by LEAK_EXPIRE;
2. You should not use LEAK_PID_CHECK here.

```
LD_PRELOAD=./libleak.so LEAK_EXPIRE=3 ./prog
```

See the README.md for detail.

**Comment by Rishi513719** [comment]
Hi WuBingzheng,

Thanks a lot for your reply. After changing the expire time LEAK_EXPIRE=3, it worked. But even after I checked the README.md file, I could not confirm the value of LEAK_EXPIRE. Sorry for my poor understanding. Could you please let me know how to decide LEAK_EXPIRE value based on program by taking my example.c program as an example. I need to apply the same to my real time application program where my application as 1 second timer as well.

Regards,
Raghu K

**Comment by Rishi513719** [comment]
Hi WuBingzheng,

I have another query as well. Kindly help me to resolve.

In real time, I have one process which is already running. I need to attach the process to get the call stack. Is there a way to do so. Kindly let me know.

Regards,
Raghu K

**Comment by WuBingzheng** [comment]
There is no clear way to choose the LEAK_EXPIRE.
You can set it as N, if you  think most of the allocated memory should be freed after N seconds. Then the memory is not freed after N seconds will be logged as leaking.
If there are too many false logging, you should increase the LEAK_EXPIRE, and try again.

you can see here https://github.com/WuBingzheng/libleak#set-expire-threshold .

**Comment by WuBingzheng** [comment]
My another tool [memleax](https://github.com/WuBingzheng/memleax) dose attach a running process to debug memory leak.
However it dose not work with multi-thread process, and makes much performance affect.
It may also crash your process. So if you real want to use it, you'd better try it at test environment first.
